### ISSUE TITLE
Errors Configuring Plugin

### ISSUE THREAD

**Issue by davidnewhall** [IndigoDomotics/alexa-hue-bridge#11]
Hello,

I hope you find this an appropriate place to reach out for support. I've been using the Alexa Hue Bridge just fine for quite a long time. I really appreciate what you've provided here; thank you!

Recently, I moved. It took me a while to get Indigo reconfigured, but I'm there now and trying to get Alexa to control my lights once more. I upgraded to the latest plugin, but immediately had errors when it loaded. I've tried many different things to make it function, but I've had no success. If me describing the "check boxes" and "ip address boxes" I went to tinkering with will help diagnose the issue, then I can be far more descriptive. I'll say: I wiped all the published devices out, disabled the plugin, re-installed, re-enabled, and in a "virgin" state it throws errors as shown below.

I hope the errors I get in the Indigo log provides some insight you can share with me. If there is a preferences file somewhere I should be nuking, please provide enlightenment.

Thank you for your time!
-david

PS. Yes, the server's IP is really 192.168.3.1, that's not the router's address.
```
   Alexa-Hue Bridge                Plugin Host IP Address overridden and specified as: '192.168.3.1'
   Alexa-Hue Bridge                Alexa discovery request logging disabled
   Alexa-Hue Bridge Warning        Debugging enabled for Alexa-Hue Bridge: General, Server, Broadcaster, Responder, Method Trace
   Reloading plugin "Alexa-Hue Bridge 3.0.18"
   Stopping plugin "Alexa-Hue Bridge 3.0.18" (pid 3979)
   Alexa-Hue Bridge                Alexa-Hue Bridge shutdown requested
   Stopped plugin "Alexa-Hue Bridge 3.0.18"
   Starting plugin "Alexa-Hue Bridge 3.0.18" (pid 3998)
   Alexa-Hue Bridge                Alexa-Hue Bridge initialising . . .
   Alexa-Hue Bridge                Plugin Host IP Address overridden and specified as: '192.168.3.1'
   Alexa-Hue Bridge                Alexa discovery request logging disabled
   Alexa-Hue Bridge Warning        Debugging enabled for Alexa-Hue Bridge: General, Server, Broadcaster, Responder, Method Trace
   Started plugin "Alexa-Hue Bridge 3.0.18"
   Alexa-Hue Bridge                Alexa-Hue Bridge initialization complete
   Alexa-Hue Bridge Error          Alexa-Hue Bridge 'Alexa Bridge' at address  either has an invalid address or invalid port 8179 - specify in Device Config
   Alexa-Hue Bridge Error          Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1165, in deviceUpdated
  File "plugin.py", line 554, in didDeviceCommPropertyChange
KeyError: ('forceDeviceStopStart',)

   Alexa-Hue Bridge                Alexa-Hue Bridge checking network access by attempting to access 'www.google.com'
   Alexa-Hue Bridge                Alexa-Hue Bridge network access check to www.google.com successfully completed.
   Alexa-Hue Bridge                Alexa-Hue Bridge checking for Plugin update
   Alexa-Hue Bridge                Checking for updates...
   Alexa-Hue Bridge                No updates are available
   Alexa-Hue Bridge                Alexa-Hue Bridge next update check scheduled for: Thursday, 2017-Nov-23 at 22:50

Nov 22, 2017, 10:50:32 PM
   Alexa-Hue Bridge                sent "Alexa Bridge" Discovery on
   Alexa-Hue Bridge Error          StandardError detected in Broadcaster.Init for 'Alexa Bridge'. Line '83' has error=''port''
   Alexa-Hue Bridge Error          StandardError detected in Responder.Init for 'Alexa Bridge'. Line '162' has error=''port''
   Alexa-Hue Bridge Error          StandardError detected in Broadcaster.Run for 'Alexa Bridge'. Line '95' has error=''discoveryExpiration''
   Alexa-Hue Bridge Error          StandardError detected in Responder.Run for 'Alexa Bridge'. Line '180' has error=''discoveryExpiration''
   Alexa-Hue Bridge                Starting Hue Bridge 'Alexa Bridge' discovery threads as 'Turn On Discovery' requested
   Alexa-Hue Bridge Error          Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1165, in deviceUpdated
  File "plugin.py", line 554, in didDeviceCommPropertyChange
KeyError: ('forceDeviceStopStart',)

   Alexa-Hue Bridge                sent "Alexa Bridge" Discovery off
   Alexa-Hue Bridge                Stop Discovery . . . . . . . . . . 
   Alexa-Hue Bridge                Stopping Hue Bridge 'Alexa Bridge' discovery threads as 'Turn Off Discovery' requested
   Alexa-Hue Bridge Error          Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7/IndigoPluginHost.app/Contents/PlugIns/plugin_base.py", line 1165, in deviceUpdated
  File "plugin.py", line 554, in didDeviceCommPropertyChange
KeyError: ('forceDeviceStopStart',)

   SQL Logger                      deleting table device_history_1454989799
   SQL Logger                      creating table device_history_115932164 for "new device"

Nov 22, 2017, 10:51:28 PM
   Alexa-Hue Bridge                'new device' updated and now has one Alexa Device published
   Alexa-Hue Bridge Error          Alexa-Hue Bridge 'new device' at address  either has an invalid address or invalid port 8178 - specify in Device Config
   Alexa-Hue Bridge Error          Alexa-Hue Bridge 'thingsauce' at address  either has an invalid address or invalid port 8180 - specify in Device Config

Nov 22, 2017, 10:51:52 PM
   Alexa-Hue Bridge                sent "thingsauce" Discovery on
   Alexa-Hue Bridge Error          StandardError detected in Broadcaster.Init for 'thingsauce'. Line '83' has error=''port''
   Alexa-Hue Bridge Error          StandardError detected in Responder.Init for 'thingsauce'. Line '162' has error=''port''
   Alexa-Hue Bridge Error          StandardError detected in Broadcaster.Run for 'thingsauce'. Line '96' has error=''Broadcaster' object has no attribute 'broadcast_packet''
   Alexa-Hue Bridge                Starting Hue Bridge 'new device' discovery threads as 'Turn On Discovery' requested
   SQL Logger                      adding column "onoffstate_ui" to table device_history_115932164 ("thingsauce")
```

**Comment by autolog** [comment]
No problem but it is better for me if you post a new thread in the [Indigo Alexa-Hue Bridge forum](http://forums.indigodomo.com/viewforum.php?f=208). :) 

Anyway, thanks for reporting and it is a bug which I have now discovered (via testing) that happens on a new install. :(

I am looking at it now and will post an announcement in the Indigo [Alexa-Hue Bridge forum](http://forums.indigodomo.com/viewforum.php?f=208) when I have fixed it. I will also update this report. :)

**Comment by autolog** [comment]
Should now be fixed in Release 3.0.19 :)

**Comment by davidnewhall** [comment]
Okay thanks! I'm in Vegas for AWS; will try again when I return home!

**Comment by davidnewhall** [comment]
Seems to work just fine now. I have another request/issue, but I'll hit up the forums for that. Thanks so much!!
