### ISSUE TITLE
Alexa Hue Bridge Discovery Off - Cannot turn back on

### ISSUE THREAD

**Issue by jsf1993** [IndigoDomotics/alexa-hue-bridge#19]
After working for a LONG time, my Indigo Alexa Hue Bridge will not work.  I ran debugger and got the following report:

Starting PuDB debugging of plugin Alexa-Hue Bridge.indigoPlugin.
To set breakpoints add indigo.debugger() calls and reload debugger.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/Alexa-Hue Bridge.indigoPlugin/Contents/Server Plugin/hue_listener.py", line 105, in run
    self.server = SocketServer.ThreadingTCPServer((PLUGIN.globals['alexaHueBridge'][self.ahbDevId]['host'], PLUGIN.globals['alexaHueBridge'][self.ahbDevId]['port']), HttpdRequestHandler)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 49] Can't assign requested address

Any help will be greatly appreciated!

Thanks!

**Comment by autolog** [comment]
Sorry, missed this :(

Has this problem been resolved?

I would encourage you to post questions/issues about the Alexa-Hue Bridge in the Indigo forums so that other users can contribute suggestions. :)

**Comment by jsf1993** [comment]
Thanks, Jon....Yes....I fixed it.   

Regards,
Jim

CONFIDENTIALITY NOTICE:  The information contained in this E-mail message is attorney privileged and confidential information intended only for the use of the individual(s) named above.  If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copy of this communication is strictly prohibited.  If you have received this communication in error, please contact the sender by reply E-mail and destroy all copies of the original message.  Thank you.
